import { z } from "zod";
import type { ClientInformation } from "@/types";

export const clientFormSchema = z
  .object({
    fullName: z.string().min(2, "Full name is required"),
    passportNumber: z.string().min(3, "Passport number is required"),
    nationality: z.string().min(2, "Nationality is required"),
    dateOfBirth: z.string().min(1, "Date of birth is required"),
    maritalStatus: z.enum([
      "single",
      "married",
      "divorced",
      "widowed",
      "separated",
    ]),
    email: z
      .string()
      .optional()
      .refine(
        (val) => !val || /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(val),
        { message: "Invalid email" }
      ),
    phone: z.string().optional(),
    currentAddress: z.string().optional(),
    cityOfResidence: z.string().optional(),
    passportIssueDate: z.string().optional(),
    passportExpiryDate: z.string().optional(),
    destinationCountry: z.string().min(2, "Destination country is required"),
    purposeOfTravel: z.string().min(3, "Purpose of travel is required"),
    visaType: z.string().optional(),
    embassyCity: z.string().optional(),
    numberOfEntries: z.string().optional(),
    travelStartDate: z.string().min(1, "Travel start date is required"),
    travelEndDate: z.string().min(1, "Travel end date is required"),
    duration: z.string().min(1, "Duration is required"),
    hostName: z.string().optional(),
    hostAddress: z.string().optional(),
    itinerary: z.string().optional(),
    occupation: z.string().optional(),
    employerName: z.string().optional(),
    employerAddress: z.string().optional(),
    employmentType: z.string().optional(),
    monthlySalary: z.string().optional(),
    annualIncome: z.string().optional(),
    employmentStartDate: z.string().optional(),
    bankBalance: z.string().optional(),
    tripFundedBy: z.string().optional(),
    travelInsuranceAvailable: z.boolean(),
    otherAssets: z.string().optional(),
    previousVisas: z.boolean(),
    countriesVisited: z.string().optional(),
    previousVisaRefusals: z.boolean(),
    previousVisaRefusalDetails: z.string().optional(),
    schengenVisasHeld: z.string().optional(),
    hotelReservationAvailable: z.boolean(),
    flightReservationAvailable: z.boolean(),
    sponsorInformation: z.string().optional(),
    familyTiesHomeCountry: z.string().optional(),
    reasonToReturn: z.string().optional(),
    consultantNotes: z.string().optional(),
    additionalNotes: z.string().optional(),
  })
  .refine(
    (data) => {
      if (!data.travelStartDate || !data.travelEndDate) return true;
      return new Date(data.travelEndDate) >= new Date(data.travelStartDate);
    },
    {
      message: "End date must be on or after start date",
      path: ["travelEndDate"],
    }
  );

export type ClientFormValues = z.infer<typeof clientFormSchema>;

export const defaultClientFormValues: ClientFormValues = {
  fullName: "",
  passportNumber: "",
  nationality: "",
  dateOfBirth: "",
  maritalStatus: "single",
  email: "",
  phone: "",
  currentAddress: "",
  cityOfResidence: "",
  passportIssueDate: "",
  passportExpiryDate: "",
  destinationCountry: "",
  purposeOfTravel: "",
  visaType: "",
  embassyCity: "",
  numberOfEntries: "",
  travelStartDate: "",
  travelEndDate: "",
  duration: "",
  hostName: "",
  hostAddress: "",
  itinerary: "",
  occupation: "",
  employerName: "",
  employerAddress: "",
  employmentType: "",
  monthlySalary: "",
  annualIncome: "",
  employmentStartDate: "",
  bankBalance: "",
  tripFundedBy: "",
  travelInsuranceAvailable: false,
  otherAssets: "",
  previousVisas: false,
  countriesVisited: "",
  previousVisaRefusals: false,
  previousVisaRefusalDetails: "",
  schengenVisasHeld: "",
  hotelReservationAvailable: false,
  flightReservationAvailable: false,
  sponsorInformation: "",
  familyTiesHomeCountry: "",
  reasonToReturn: "",
  consultantNotes: "",
  additionalNotes: "",
};

export function toClientInformation(values: ClientFormValues): ClientInformation {
  return {
    fullName: values.fullName,
    passportNumber: values.passportNumber,
    nationality: values.nationality,
    dateOfBirth: values.dateOfBirth,
    maritalStatus: values.maritalStatus,
    email: values.email ?? "",
    phone: values.phone ?? "",
    currentAddress: values.currentAddress ?? "",
    cityOfResidence: values.cityOfResidence ?? "",
    passportIssueDate: values.passportIssueDate ?? "",
    passportExpiryDate: values.passportExpiryDate ?? "",
    destinationCountry: values.destinationCountry,
    purposeOfTravel: values.purposeOfTravel,
    visaType: values.visaType ?? "",
    embassyCity: values.embassyCity ?? "",
    numberOfEntries: values.numberOfEntries ?? "",
    travelStartDate: values.travelStartDate,
    travelEndDate: values.travelEndDate,
    duration: values.duration,
    hostName: values.hostName ?? "",
    hostAddress: values.hostAddress ?? "",
    itinerary: values.itinerary ?? "",
    occupation: values.occupation ?? "",
    employerName: values.employerName ?? "",
    employerAddress: values.employerAddress ?? "",
    employmentType: values.employmentType ?? "",
    monthlySalary: values.monthlySalary ?? "",
    annualIncome: values.annualIncome ?? "",
    employmentStartDate: values.employmentStartDate ?? "",
    bankBalance: values.bankBalance ?? "",
    tripFundedBy: values.tripFundedBy ?? "",
    travelInsuranceAvailable: values.travelInsuranceAvailable,
    otherAssets: values.otherAssets ?? "",
    previousVisas: values.previousVisas,
    countriesVisited: values.countriesVisited ?? "",
    previousVisaRefusals: values.previousVisaRefusals,
    previousVisaRefusalDetails: values.previousVisaRefusalDetails ?? "",
    schengenVisasHeld: values.schengenVisasHeld ?? "",
    hotelReservationAvailable: values.hotelReservationAvailable,
    flightReservationAvailable: values.flightReservationAvailable,
    sponsorInformation: values.sponsorInformation ?? "",
    familyTiesHomeCountry: values.familyTiesHomeCountry ?? "",
    reasonToReturn: values.reasonToReturn ?? "",
    consultantNotes: values.consultantNotes ?? "",
    additionalNotes: values.additionalNotes ?? "",
  };
}
